timeout: 5
serial: yes
verbose: yes

/BoruixOS
protocol: limine
kernel_path: boot():/kernel.elf
module_path: boot():/initproc
module_path: boot():/loop_a
module_path: boot():/loop_b
module_path: boot():/rogue
module_path: boot():/testsmp1
module_path: boot():/race
module_path: boot():/ipi
module_path: boot():/memstress
cmdline: hello
comment: Boruix OS via Limine
